### ISSUE TITLE
Can't migrate

### ISSUE THREAD

**Issue by fcouceiro** [clubeprogramacao/Website#1]
I've pulled the latest changes and when I try to rollback and run again all migrations I'm getting this error:

![error image](http://s33.postimg.org/rq8urz4lr/Captura_de_ecra_2016_05_23_a_s_18_37_28.png)

**Comment by rscmendes** [comment]
There are two problems concerning this error. The first one is that this class (and the database table programming_language_user) had been renamed without refactor and thus some "laravel internals" weren't updated. Created a fresh new migration with the same name and that problem is solved.

Also had to add, to courses and roles tables: (for problem number 2)
DB::statement('SET FOREIGN_KEY_CHECKS = 0');
Schema::drop('tableName');
DB::statement('SET FOREIGN_KEY_CHECKS = 1');

refresh and rollback now properly working.

**Comment by fcouceiro** [comment]
Okay. Will check if it works! ;) Thanks

**Comment by fcouceiro** [comment]
I'm still having the same issue. I've recreated the database schema and ran the migrations without problem. If I try to refresh (php artisan migrate:refresh) it throws the same error. At least for now it'll do, but I think we should fix this before production. Or else we can loose our customers data easily, with a simple migration update in the future.
